#!/bin/bash
#important: enable spi but do not connect devices untill AFTER install
sudo apt install python3-pip vim git libboost-python-dev python3-picamera python3-pil python3-smbus
sudo python3 -m pip install pyserial pynmea2 luma.oled
mkdir ~/rf24libs
cd ~/rf24libs
git clone https://github.com/tmrh20/RF24.git RF24
cd RF24 
./configure --driver=SPIDEV
make
sudo make install
cd pyRF24 
python3 setup.py build
sudo python3 setup.py install

# copy fonts in dropbox /home/curt/Dropbox/tnkerProjects/piTFT to /usr/share/fonts/
