#!/bin/bash

sudo apt install python3-pip vim git libboost-python-dev

mkdir ~/rf24libs
cd ~/rf24libs
git clone https://github.com/tmrh20/RF24.git RF24
cd RF24 
./configure --driver=SPIDEV
make
sudo make install
cd pyRF24 
python3 setup.py build
sudo python3 setup.py install
sudo python3 -m pip install pyserial pynmea2 luma.oled
sudo apt install python3-picamera python3-pil python3-rpi.gpio python3-spidev python3-smbus
# copy fonts in dropbox /home/curt/Dropbox/tnkerProjects/piTFT to /usr/share/fonts/
